"""empty message

Revision ID: e5bda1938413
Revises: 
Create Date: 2022-05-31 19:10:22.592454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bda1938413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TAUData',
    sa.Column('user_mail', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.ForeignKeyConstraint(['user_mail'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('user_mail', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TAUData')
    # ### end Alembic commands ###
